### ISSUE TITLE
ProcessBatchWork crash.

### ISSUE THREAD

**Issue by reloadedandrovald** [microsoft/D3D12TranslationLayer#3] opened 2020-03-17 04:59 UTC
OS: Windows 10 Pro, Version 1903, OS Build 18362.657
DLL: d3d11on12.dll, version 10.0.18362.387, WinBuild.160101.0800
PDB Signature: 6e29daca7e48d493f5fe671202e9d6c51 (d3d11on12.pdb from Microsoft Symbol Servers)

After trying to debug an issue with the latest version of pix, causing the game I'm currently working on to crash, I ended up in the D3D12TranslationLayer::BatchedContext::ProcessBatchWork function. Though this appears to be a compiler issue. After going through the disassembly of the function, I found that it ends up basically trying to read data from rcx + 8 + rcx * 8.

This is a 100% crash during Present. 
[D3D12TL_MarkedDissassembly.txt](https://github.com/microsoft/D3D12TranslationLayer/files/4341535/D3D12TL_MarkedDissassembly.txt) (I've marked the crashing line with >>)

**Comment by jenatali** [comment] 2020-03-17 16:08
It's trying to read data from *(this + 8) + (commandId * 8), since ecx is assigned as a result of reading the data out of the batch buffer.

Can you provide any repro code or binaries?

**Comment by reloadedandrovald** [comment] 2020-03-17 19:03
Ah, I see where I missed the ECX write. I'll try to get a bit more detail on this crash then. After updating windows to version 1909, it appears to get a little further, namely into the command dispatcher, to execute some command. 

I did however find that things appear to work when not using the ID3DUserDefinedAnnotation interface, so I am expecting the issue lies there.

**Comment by jenatali** [comment] 2021-05-26 19:14
I'm going to go ahead and close this since we don't have a way to reproduce on our side. If this is still hitting and you can provide a way to reproduce it, go ahead and reactivate.

**Closed by jenatali** 2021-05-26 19:14 UTC
